# Generated by Django 4.2.1 on 2023-05-24 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cedula',
            field=models.CharField(default='Valor predeterminado', max_length=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_entrada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='placa_vehiculo',
            field=models.CharField(default='Valor predeterminado', max_length=20),
        ),
    ]
