# Generated by Django 4.2.1 on 2023-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_fecha_reserva_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_entrada',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_solicitud',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cedula',
            field=models.CharField(default='Valor predeterminado', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='placa_vehiculo',
            field=models.CharField(default='Valor predeterminado', max_length=20),
        ),
    ]
