# Generated by Django 4.2.1 on 2023-05-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_rename_fecha_entrada_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha',
            new_name='fecha_reservada',
        ),
    ]
