# Generated by Django 4.2.1 on 2023-05-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_rename_fecha_reserva_fecha_reservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cedula',
            field=models.CharField(default='CC', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='placa_vehiculo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
