# Generated by Django 4.2.1 on 2023-05-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_reserva_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_entrada',
            new_name='fecha_entrada',
        ),
    ]
