# Generated by Django 4.2.1 on 2023-05-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_rename_hora_entrada_reserva_fecha_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_reservada',
            field=models.CharField(default='', max_length=50),
        ),
    ]
